version: '3'

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - fl-net

  client1:
    build: ./client
    networks:
      - fl-net
    depends_on:
      - server

  client2:
    build: ./client
    networks:
      - fl-net
    depends_on:
      - server

  client3:
    build: ./client
    networks:
      - fl-net
    depends_on:
      - server

networks:
  fl-net:
    driver: bridge
