version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "3000:3000"

  client:
    build: ./client
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:3000
    deploy:
      replicas: 10
