version: '3.8'

services:
  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    networks:
      - fl-net
    volumes:
      - ./server:/app
  client:
    image: lukechilds/dockerpi
    networks:
      - fl-net
    depends_on:
      - server
    volumes:
      - ./client:/app
      
networks:
  fl-net: