version: '3'
services:
  raspberry:
    build: .
    environment:
      - SERVER_ADDRESS=server:8080
    deploy:
      replicas: 10
    depends_on:
      - server
  server:
    image: python:3.9-slim
    volumes:
      - .:/app
    working_dir: /app
    command: python server.py
