services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: flwr_server_raspberry
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
    networks:
      - flwr_network_raspberry
    deploy:
      resources:
        limits:
          cpus: '0.5'  

  client:
    build:
      context: .
      dockerfile: Dockerfile.RaspberryClient
    depends_on:
      - server
    networks:
      - flwr_network_raspberry
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
    deploy:
      resources:
        limits:
          cpus: '5'  

networks:
  flwr_network_raspberry:
    driver: bridge
