services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: flwr_server
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
    networks:
      - flwr_network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
    #environment:
    #  - GRPC_ENABLE_FORK_SUPPORT=0

networks:
  flwr_network:
    driver: bridge
