# docker-compose.yml
version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: flwr_server
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data  # Mappa la cartella dei dati
      - ./performance:/app/performance  # Mappa la cartella per i report
    networks:
      - flwr_network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data  # Condividi la cartella dei dati
      - ./performance:/app/performance  # Opzionale: se i client devono accedere ai report

networks:
  flwr_network:
    driver: bridge

volumes:
  data:
  performance:
