services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: flwr_server_raspberry
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
    networks:
      - flwr_network
    deploy:
      resources:
        limits:
          cpus: '0.5'   

  client:
    build:
      context: .
      dockerfile: Dockerfile.RaspberryClient
    depends_on:
      - server
    networks:
      - flwr_network
    volumes:
      - ./data:/app/data
      - ./performance:/app/performance
    #environment:
    #  - GRPC_ENABLE_FORK_SUPPORT=0
    deploy:
      resources:
        limits:
          cpus: '5'

networks:
  flwr_network:
    driver: bridge
